/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesCopperRepipeRouteImport } from './routes/services.copper-repipe'
import { Route as ServicesGeneralPlumbingRouteImport } from './routes/services.general-plumbing'
import { Route as ServicesLeakDetectionRouteImport } from './routes/services.leak-detection'
import { Route as ServicesPexRepipeRouteImport } from './routes/services.pex-repipe'
import { Route as ServicesSewerCameraRouteImport } from './routes/services.sewer-camera'
import { Route as ServicesSlabLeakRouteImport } from './routes/services.slab-leak'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCopperRepipeRoute = ServicesCopperRepipeRouteImport.update({
  id: '/services/copper-repipe',
  path: '/services/copper-repipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGeneralPlumbingRoute = ServicesGeneralPlumbingRouteImport.update({
  id: '/services/general-plumbing',
  path: '/services/general-plumbing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLeakDetectionRoute = ServicesLeakDetectionRouteImport.update({
  id: '/services/leak-detection',
  path: '/services/leak-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPexRepipeRoute = ServicesPexRepipeRouteImport.update({
  id: '/services/pex-repipe',
  path: '/services/pex-repipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSewerCameraRoute = ServicesSewerCameraRouteImport.update({
  id: '/services/sewer-camera',
  path: '/services/sewer-camera',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlabLeakRoute = ServicesSlabLeakRouteImport.update({
  id: '/services/slab-leak',
  path: '/services/slab-leak',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/outreach': typeof OutreachRoute
  '/testimonials': typeof TestimonialsRoute
  '/work': typeof WorkRoute
  '/services/copper-repipe': typeof ServicesCopperRepipeRoute
  '/services/general-plumbing': typeof ServicesGeneralPlumbingRoute
  '/services/leak-detection': typeof ServicesLeakDetectionRoute
  '/services/pex-repipe': typeof ServicesPexRepipeRoute
  '/services/sewer-camera': typeof ServicesSewerCameraRoute
  '/services/slab-leak': typeof ServicesSlabLeakRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/outreach': typeof OutreachRoute
  '/testimonials': typeof TestimonialsRoute
  '/work': typeof WorkRoute
  '/services/copper-repipe': typeof ServicesCopperRepipeRoute
  '/services/general-plumbing': typeof ServicesGeneralPlumbingRoute
  '/services/leak-detection': typeof ServicesLeakDetectionRoute
  '/services/pex-repipe': typeof ServicesPexRepipeRoute
  '/services/sewer-camera': typeof ServicesSewerCameraRoute
  '/services/slab-leak': typeof ServicesSlabLeakRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/outreach': typeof OutreachRoute
  '/testimonials': typeof TestimonialsRoute
  '/work': typeof WorkRoute
  '/services/copper-repipe': typeof ServicesCopperRepipeRoute
  '/services/general-plumbing': typeof ServicesGeneralPlumbingRoute
  '/services/leak-detection': typeof ServicesLeakDetectionRoute
  '/services/pex-repipe': typeof ServicesPexRepipeRoute
  '/services/sewer-camera': typeof ServicesSewerCameraRoute
  '/services/slab-leak': typeof ServicesSlabLeakRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/outreach'
    | '/testimonials'
    | '/work'
    | '/services/copper-repipe'
    | '/services/general-plumbing'
    | '/services/leak-detection'
    | '/services/pex-repipe'
    | '/services/sewer-camera'
    | '/services/slab-leak'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/outreach'
    | '/testimonials'
    | '/work'
    | '/services/copper-repipe'
    | '/services/general-plumbing'
    | '/services/leak-detection'
    | '/services/pex-repipe'
    | '/services/sewer-camera'
    | '/services/slab-leak'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/outreach'
    | '/testimonials'
    | '/work'
    | '/services/copper-repipe'
    | '/services/general-plumbing'
    | '/services/leak-detection'
    | '/services/pex-repipe'
    | '/services/sewer-camera'
    | '/services/slab-leak'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  OutreachRoute: typeof OutreachRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WorkRoute: typeof WorkRoute
  ServicesCopperRepipeRoute: typeof ServicesCopperRepipeRoute
  ServicesGeneralPlumbingRoute: typeof ServicesGeneralPlumbingRoute
  ServicesLeakDetectionRoute: typeof ServicesLeakDetectionRoute
  ServicesPexRepipeRoute: typeof ServicesPexRepipeRoute
  ServicesSewerCameraRoute: typeof ServicesSewerCameraRoute
  ServicesSlabLeakRoute: typeof ServicesSlabLeakRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/copper-repipe': {
      id: '/services/copper-repipe'
      path: '/services/copper-repipe'
      fullPath: '/services/copper-repipe'
      preLoaderRoute: typeof ServicesCopperRepipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/general-plumbing': {
      id: '/services/general-plumbing'
      path: '/services/general-plumbing'
      fullPath: '/services/general-plumbing'
      preLoaderRoute: typeof ServicesGeneralPlumbingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/leak-detection': {
      id: '/services/leak-detection'
      path: '/services/leak-detection'
      fullPath: '/services/leak-detection'
      preLoaderRoute: typeof ServicesLeakDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/pex-repipe': {
      id: '/services/pex-repipe'
      path: '/services/pex-repipe'
      fullPath: '/services/pex-repipe'
      preLoaderRoute: typeof ServicesPexRepipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/sewer-camera': {
      id: '/services/sewer-camera'
      path: '/services/sewer-camera'
      fullPath: '/services/sewer-camera'
      preLoaderRoute: typeof ServicesSewerCameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/slab-leak': {
      id: '/services/slab-leak'
      path: '/services/slab-leak'
      fullPath: '/services/slab-leak'
      preLoaderRoute: typeof ServicesSlabLeakRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  OutreachRoute: OutreachRoute,
  TestimonialsRoute: TestimonialsRoute,
  WorkRoute: WorkRoute,
  ServicesCopperRepipeRoute: ServicesCopperRepipeRoute,
  ServicesGeneralPlumbingRoute: ServicesGeneralPlumbingRoute,
  ServicesLeakDetectionRoute: ServicesLeakDetectionRoute,
  ServicesPexRepipeRoute: ServicesPexRepipeRoute,
  ServicesSewerCameraRoute: ServicesSewerCameraRoute,
  ServicesSlabLeakRoute: ServicesSlabLeakRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
